name: Cyris
version: "1.0"
main: de.tzimon.cyris.Cyris
author: Tzimon
authors:
  - Tzimon
  - xQuiesel

commands:
  home:
    usage: /home <HomeName|HomeID>
    description: Teleports you to your home
  sethome:
    usage: /sethome <HomeName>
    description: Creates a home or replaces an existing one
  deletehome:
    usage: /deletehome <HomeName|HomeID>
    description: Deletes a home
    aliases: [delhome]
  homes:
    usage: /homes
    description: Shows you a list of all your homes
    aliases: [homelist]
  travel:
    usage: /travel [<X> <Z>]
    description: Creates or deletes a travel point